const weatherCodes = {
  0: { desc: "Despejado", icon: "☀️" },
  1: { desc: "Principalmente despejado", icon: "🌤️" },
  2: { desc: "Parcialmente nublado", icon: "⛅" },
  3: { desc: "Nublado", icon: "☁️" },
  45: { desc: "Niebla", icon: "🌫️" },
  48: { desc: "Niebla con escarcha", icon: "🌫️" },
  51: { desc: "Llovizna ligera", icon: "🌦️" },
  53: { desc: "Llovizna moderada", icon: "🌦️" },
  55: { desc: "Llovizna intensa", icon: "🌦️" },
  56: { desc: "Llovizna ligera helada", icon: "🌧️❄️" },
  57: { desc: "Llovizna intensa helada", icon: "🌧️❄️" },
  61: { desc: "Lluvia ligera", icon: "🌧️" },
  63: { desc: "Lluvia moderada", icon: "🌧️" },
  65: { desc: "Lluvia intensa", icon: "🌧️" },
  66: { desc: "Lluvia helada ligera", icon: "🌧️❄️" },
  67: { desc: "Lluvia helada intensa", icon: "🌧️❄️" },
  71: { desc: "Nieve ligera", icon: "🌨️" },
  73: { desc: "Nieve moderada", icon: "🌨️" },
  75: { desc: "Nieve intensa", icon: "❄️" },
  77: { desc: "Granos de nieve", icon: "🌨️" },
  80: { desc: "Chubascos ligeros", icon: "🌦️" },
  81: { desc: "Chubascos moderados", icon: "🌦️" },
  82: { desc: "Chubascos violentos", icon: "🌧️" },
  85: { desc: "Chubascos de nieve ligeros", icon: "🌨️" },
  86: { desc: "Chubascos de nieve intensos", icon: "❄️" },
  95: { desc: "Tormenta ligera o moderada", icon: "⛈️" },
  96: { desc: "Tormenta con granizo ligero", icon: "⛈️" },
  99: { desc: "Tormenta con granizo intenso", icon: "⛈️" },
};
export default weatherCodes;
